name: youtube_analytics_lakehouse
version: '1.0'
config-version: 2

profile: youtube_analytics_lakehouse

model-paths: ["models"]

models:
  youtube_analytics_lakehouse:

    silver:
      +materialized: table
      +schema: youtube_silver

    gold:
      +materialized: table
      +schema: youtube_gold